FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD testhls1.jar /opt/testhls1/
EXPOSE 8080
WORKDIR /opt/testhls1/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "testhls1.jar"]
