FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD Devops7.jar /opt/Devops7/
EXPOSE 8080
WORKDIR /opt/Devops7/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "Devops7.jar"]
